### PR TITLE
Fix explorer opening issue in electron

### LINKED ISSUE #1116: The Skycoin Explorer in desktop client doesn't work
Instead of opening the explorer in browser, it tries to load it in the client, and result in blank page like this:

image

### PR DESCRIPTION
**Pull request by iketheadore**
Fixes #1116 
 

Does this change need to mentioned in CHANGELOG.md?
No

### CODE REVIEW

**Comment by iketheadore** [comment]
I will resend a PR, this one includes the Bump version 0.22.0 commits, which be merged after this one.

File: electron/src/electron-main.js [hunk 1]
```diff
@@ -174,7 +165,12 @@ function createWindow(url) {
     // in an array if your app supports multi windows, this is the time
     // when you should delete the corresponding element.
     win = null;
-});
+  });
+
+  win.webContents.on('will-navigate', function(e, url) {
```
Comment (gz-c) [inline electron/src/electron-main.js]: This doesnt affect the other wallet links?

Comment (iketheadore) [reply electron/src/electron-main.js]: No, it doesn't affect the others.
