### PR TITLE
Update/fix visor tests

### LINKED ISSUE #401: Update/fix visor tests
Some of the visor test files cannot compile so are marked `// +build ignore`.  These tests should be amended or removed as necessary.

### PR DESCRIPTION
**Pull request by Vavilen**
Done: visor/readable_test.go
Fixes #401

### CODE REVIEW

File: src/visor/readable_test.go [hunk 1]
```diff
@@ -1,343 +1,274 @@
...
+func setupVisor(t *testing.T) (v *Visor, close func()) {
+	db, close := testutil.PrepareDB(t)
+	vc := setupVisorConfig(t)
+	v, err := NewVisor(vc, db)
+	require.NoError(t, err)
+	return
+}
+
+func cleanupVisor(dir string) {
+	err := os.RemoveAll(dir)
```
Comment (gz-c) [inline src/visor/readable_test.go]: Don't do this, in case there is a bug and we call os.RemoveAll on the wrong directory (this happened before)

Just leave the temp folders in temp

Comment (Vavilen) [reply src/visor/readable_test.go]: @gz-c , fixed.
Do I need remove wallet files?

**Comment by gz-c** [comment]
@iketheadore please review
