### PR TITLE
Fix flaky test error in TestHistorydbVerifier

### LINKED ISSUE #1742: Flaky error in TestHistorydbVerifier
```go
--- FAIL: TestHistorydbVerifier (0.03s)
    --- FAIL: TestHistorydbVerifier/missing_uxout (0.01s)
     assertions.go:239: 
                          
 Error Trace: visor_test.go:249
      
 Error:       Not equal: 
      
              expected: historydb.ErrHistoryDBCorrupted{error:(*errors.errorString)(0xc420cac690)}
      
              actual: historydb.ErrHistoryDBCorrupted{error:(*errors.errorString)(0xc420a88cb0)}

              Diff:
      
              --- Expected
      
              +++ Actual
      
              @@ -1,2 +1,2 @@
      
              -(historydb.ErrHistoryDBCorrupted) HistoryDB.Verify: transaction input 2f87d77c2a7d00b547db1af50e0ba04bafc5b05711e4939e9ec2640a21127dc0 does not exist in historydb
      
              +(historydb.ErrHistoryDBCorrupted) HistoryDB.Verify: transaction output 2f87d77c2a7d00b547db1af50e0ba04bafc5b05711e4939e9ec2640a21127dc0 does not exist in historydb
```

### PR DESCRIPTION
**Pull request by iketheadore**
Fixes #1742 

Changes:
- Use regexp error to do error match
- Remove ### Setup section in electron/README, electron does not use yarn anymore and the build script will run npm install automatically.

Does this change need to mentioned in CHANGELOG.md?
No

### CODE REVIEW

File: src/visor/visor_test.go [hunk 1]
```diff
@@ -246,7 +247,15 @@ func TestHistorydbVerifier(t *testing.T) {
...
 
 			err = bc.WalkChain(2, f, nil)
-			require.Equal(t, tc.expectErr, err)
+			if tc.expectErr == nil {
+				require.Nil(t, err)
+				return
+			}
+
+			// Confirms that the error type is matched
+			require.Equal(t, reflect.TypeOf(tc.expectErr), reflect.TypeOf(err))
```
Comment (gz-c) [inline src/visor/visor_test.go]: Can use `require.IsType`
