### PR TITLE
Fix too many outgoing connections on start

### LINKED ISSUE #1546: Client makes too many outgoing connections on start
When running Little snitch, which blocks outgoing connections until approved, the client will try to initiate a lot of connections, e.g. 118 pending outgoing connections.

### PR DESCRIPTION
**Pull request by iketheadore**
Fixes #1546

Changes:
- Fix too many outgoing connections on start

Does this change need to mentioned in CHANGELOG.md?
No

### CODE REVIEW

File: src/daemon/daemon.go [hunk 1]
```diff
@@ -867,6 +869,19 @@ func (dm *Daemon) onConnect(e ConnectEvent) {
...
 
 	if e.Solicited {
+		// Disconnect if the max outgoing connections is reached
+		n, err := dm.Pool.Pool.Size()
+		if err != nil {
+			logger.WithError(err).Error("get connection pool size failed")
+			return
+		}
+
+		if n > dm.Config.OutgoingMax {
```
Comment (gz-c) [inline src/daemon/daemon.go]: Doesn't pool size include both incoming and outgoing?

Comment (iketheadore) [reply src/daemon/daemon.go]: Oh yes, will update
